const assert=require('node:assert/strict');
const E=require('./dist/engine.js');
const s=E.create();
const routine=E.add(s,{urgency:'Low',need:'ICU Bed',risk:2});
const critical=E.add(s,{urgency:'Critical',need:'ICU Bed',risk:10});
assert.equal(E.ordered(s)[0],critical);
s.resources['ICU Bed'].used=4;
assert.match(E.blocked(s,routine),/reserve/);
assert.equal(E.blocked(s,critical),'');
E.dispatch(s);assert.equal(critical.status,'In treatment');assert.equal(routine.status,'Waiting');
assert.equal(s.resources['ICU Bed'].used,5);assert.equal(s.resources.Doctor.used,1);
E.finish(s,critical);assert.equal(s.resources['ICU Bed'].used,5);assert.equal(s.resources.Doctor.used,0);
const bed=s.turnover[0].id;E.turn(s,bed);E.turn(s,bed);assert.equal(s.resources['ICU Bed'].used,5);E.turn(s,bed);assert.equal(s.resources['ICU Bed'].used,4);assert.equal(E.turn(s,bed),false);
const a=E.create();a.resources.Nurse.used=a.resources.Nurse.total;const p=E.add(a,{urgency:'Critical',need:'Ventilator'});E.dispatch(a);assert.equal(a.resources.Ventilator.used,0);assert.equal(a.resources['ICU Bed'].used,0);assert.equal(p.status,'Waiting');
const b=E.create();for(let i=0;i<6;i++)E.add(b,{urgency:'High',need:'Doctor',duration:8});const p6=b.patients[5];assert.equal(E.eta(b,p6).minutes,8);b.doctors.forEach(d=>d.history=[4,4,4]);assert.equal(E.eta(b,p6).minutes,4);E.dispatch(b);assert.equal(b.resources.Doctor.used,4);assert.equal(new Set(b.patients.filter(p=>p.doctor).map(p=>p.doctor)).size,4);
const aged=E.add(b,{urgency:'Low',wait:50});assert(E.score(aged)>E.score({...aged,wait:0}));
const stress=E.create();for(let i=0;i<100;i++)E.add(stress,{urgency:['Critical','High','Medium','Low'][i%4],risk:i%10+1,need:['Doctor','ER Bed','ICU Bed','Ventilator','Operating Room'][i%5],duration:i%10+2});E.dispatch(stress);for(let t=0;t<500;t++){E.step(stress,'smart',true);assert.deepEqual(E.violations(stress),[])}assert(stress.patients.every(p=>p.status==='Completed'));
const snapshot=JSON.stringify(b);const compare=E.comparison(b);assert.equal(JSON.stringify(b),snapshot);assert.equal(compare.length,2);assert(compare.every(r=>r.served===r.total&&r.conflicts===0));
console.log('PASS: priority, reserve, atomic allocation, doctor exclusivity, turnover, dynamic ETA, aging, 100-patient stress and fair snapshot isolation');
